### ISSUE TITLE
Multiplatform 

### ISSUE THREAD

**Issue by ShalokShalom** [isenmann/OpenSaberVR#13]
:hugs: 

Hi and thanks a lot for this one. I see C#, I see Unity3D and my limited understanding asks why this is not cross platform? Unity can do this, or?

^-^

**Comment by isenmann** [comment]
Do you mean Linux or other headsets like Oculus Quest?

**Comment by ShalokShalom** [comment]
OK, thanks a lot. ^-^

You could simply ask in the README for support like that. 

Greez
